Update Rust project READMEs
dfinity/examples pull request #1073
Opened 2024-12-19 21:40 UTC by jessiemongeon1

**Overview**
Why do we need this feature? What are we trying to accomplish?

**Requirements**
What requirements are necessary to consider this problem solved?

**Considered Solutions**
What solutions were considered?

**Recommended Solution**
What solution are you recommending? Why?

**Considerations**
What impact will this change have on security, performance, users (e.g. breaking changes) or the team (e.g. maintenance costs)?

2024-12-19 21:50 UTC, berestovskyy approved these changes

2024-12-20 06:41 UTC, gregorydemay approved these changes
Thanks for the clean-up, cross-chain changes LGTM!

2024-12-23 10:24 UTC, oggy-dfin submitted a review, later dismissed

2024-12-27 21:44 UTC, ericswanson-dfinity submitted a review, later dismissed

2025-01-03 21:46 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> +```
This part wasn't there before. It seems this comes from the respective Motoko example (see [this](https://github.com/dfinity/examples/blob/master/motoko/threshold-schnorr/README.md?plain=1#L63-L64)) but for Rust, the @noble/curves NPM dependency is not needed.

I suggest to just remove this part, together with lines 56 and 57.

2025-01-03 21:46 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> -`sign`, and `verify` methods, those are rendered in the web UI.
The Rust example does expose a `verify` method, so this is actually correct. (The Motoko example doesn't)

2025-01-03 21:46 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> -
I have the impression that the new text for this Rust threshold-schnorr example README was copy/pasted from the respective Motoko variant and adapted, but that is actually not correct as the two examples function somewhat different.

For example, the Motoko example mentions a way to test the canister with Javascript, while the Rust example does all the testing directly in Rust.

It seems all changes in this file from here on should be discarded. (Granted, there a few issues in the text, but these seem minor; for example `lib.rs` should be `wasm_only.rs`.)

2025-01-03 21:58 UTC, jessiemongeon1 commented on rust/threshold-ecdsa/README.md
> +To deploy the sample code, the canister needs the right key ID for the right environment. Specifically, one needs to replace the value of the `key_id` in the `src/ecdsa_example_rust/main.mo` file of
```suggestion
To deploy the sample code, the canister needs the right key ID for the right environment. Specifically, one needs to replace the value of the `key_id` in the `src/ecdsa_example_rust/src/lib.rs` file of the sample code. Before deploying to the mainnet, one should modify the code to use the right name of the `key_id`.
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-ecdsa/README.md
> +> To deploy to IC mainnet, one needs to replace the value in `key_id` fields with the values `"dfx_test_key"` to instead have either `"test_key_1"` or `"key_1"` depending on the desired intent.
```suggestion
> To deploy to IC mainnet, one needs to replace the value in `key_id `fields with the values `EcdsaKeyIds::TestKeyLocalDevelopment.to_key_id()` (mapping to `dfx_test_key`) to instead have either `EcdsaKeyIds::TestKey1.to_key_id()` (mapping to `test_key_1`) or `EcdsaKeyIds::ProductionKey1.to_key_id()` (mapping to `key_1`) depending on the desired intent.
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +npm install @noble/curves
```suggestion

```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +- `make test` deploys and tests the canister code on the local version of the IC
```suggestion

```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +public methods the canister exposes. Since the canister exposes `public_key` and
```suggestion
`sign`, and `verify` methods, those are rendered in the web UI.
public methods the canister exposes. Since the canister exposes `public_key` and
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +IMPORTANT: To deploy to IC mainnet, one needs to replace `"dfx_test_key"` with
```suggestion
For example, the default code in `src/schnorr_example_rust/src/lib.rs` derives
the key ID as follows and can be deployed locally:
`SchnorrKeyIds::TestKeyLocalDevelopment.to_key_id(algorithm)`

IMPORTANT: To deploy to IC mainnet, one needs to replace `"dfx_test_key"` with
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +### Deploying
```suggestion

IMPORTANT: To deploy to IC mainnet, one needs to replace
`SchnorrKeyIds::TestKeyLocalDevelopment` (which maps to the `"dfx_test_key"` key
id) with either `SchnorrKeyIds::TestKey1` (`"test_key_1"`) or
`SchnorrKeyIds::ProductionKey1` (`"key_1"`) depending on the desired intent.
Both uses of key ID in `src/schnorr_example_rust/src/lib.rs` must be consistent.

### Deploying
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +The implementation of this canister in Rust is (`schnorr_example_rust`) is
```suggestion
The implementation of this canister in Rust (`schnorr_example_rust`) is
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +deployed on mainnet. It has the URL
```suggestion
deployed on the mainnet. It has the URL
```

2025-01-03 22:09 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +mainnet.
```suggestion
the mainnet.
```

2025-01-03 22:14 UTC, jessiemongeon1 commented on rust/x509/README.md
> +The minimum version of `dfx` thatrun this example locally is
```suggestion
```

2025-01-03 22:14 UTC, jessiemongeon1 commented on rust/x509/README.md
>  -   [x] Clone the example dapp project: `git clone https://github.com/dfinity/examples`
```suggestion

```

2025-01-03 22:14 UTC, jessiemongeon1 commented on rust/x509/README.md
> +To deploy this canister the mainnet, you must do two things:
```suggestion
Before deploying this canister to the mainnet, you must do the following:
```

2025-01-03 23:19 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> +```
@jessiemongeon1, you marked this conversation as resolved, but it actually isn't resolved and my comment still stands: lines 48 to 52 should be removed, along with lines 56 and 57. So I'm unresolving this conversation.

Update: I see you created some [suggestions like this](https://github.com/dfinity/examples/pull/1073#discussion_r1902199341) for this file, but somehow they were not applied correctly by Github!?

2025-01-03 23:19 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> -`sign`, and `verify` methods, those are rendered in the web UI.
@jessiemongeon1, you marked this conversation as resolved, but it actually isn't resolved and my comment still stands, so I'm unresolving this conversation.

2025-01-03 23:19 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> +key ID in `src/schnorr_example_rust/src/main.mo` must be consistent.
@jessiemongeon1, you marked this conversation as resolved, but it actually isn't resolved and my comment still stands (now the old line numbers are 121-126), so I'm unresolving this conversation.

2025-01-03 23:19 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> +path path. Note that the first byte of the BIP340 public key needs to be removed for
Now the word "path" is duplicated here ("path path").

2025-01-03 23:19 UTC, fspreiss commented on rust/threshold-schnorr/README.md
> -
Not sure why this code block shall be deleted. IMO, it should be kept as-is.

2025-01-06 14:51 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +```
Yes, it looks like GitHub did not apply my edits to revise this correctly. I've re-applied the revisions. My apologies.

2025-01-06 14:51 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> +key ID in `src/schnorr_example_rust/src/main.mo` must be consistent.
It looks like GitHub did not apply my edits to revise this correctly. I've re-applied the revisions. My apologies.

2025-01-06 14:52 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> -`sign`, and `verify` methods, those are rendered in the web UI.
It looks like GitHub did not apply my edits to revise this correctly. I've re-applied the revisions. My apologies.

2025-01-06 15:04 UTC, jessiemongeon1 commented on rust/threshold-schnorr/README.md
> -
Not sure what happened here; this was not intended to be removed.

2025-01-07 08:42 UTC, fspreiss approved these changes
Thanks for addressing the comments, @jessiemongeon1. I have one final comment.

2025-01-07 08:42 UTC, fspreiss commented on rust/threshold-ecdsa/README.md
> +## Step 1: Setup the project environment
Maybe group Step 1 and Step 2 (and possibly the Prerequisites) into a Local Deployment parent, similar to how you did the same in the Motoko READMEs in the other PR.

Same for threshold-schnorr.

2025-01-07 12:13 UTC, maksymar approved these changes

2025-01-07 20:53 UTC, berestovskyy approved these changes

2025-01-07 21:49 UTC, marc0olo commented on rust/icp_transfer/README.md
> +> Make sure that you are using the default `dfx` account that we minted tokens to in step 7 for the following steps.
```suggestion
> Make sure that you are using the default `dfx` account that we minted tokens to in step 6 for the following steps.
```

2025-01-07 21:50 UTC, marc0olo commented on rust/pub-sub/README.md
>  dfx canister call subscriber setup_subscribe '(principal "<publisher ID from Step 3>", "Apples")'
```suggestion
dfx canister call subscriber setup_subscribe '(principal "<publisher ID from Step 2>", "Apples")'
```

2025-01-07 21:54 UTC, marc0olo requested changes
@jessiemongeon1 made some comments for wrong step references which should be fixed. maybe there are other READMEs where this is relevant. I only looked at the READMEs where the growth team is owner.

2025-01-08 00:49 UTC, krpeacock approved these changes

2025-01-08 07:00 UTC, gregorydemay approved these changes

2025-01-08 09:29 UTC, Sawchord approved these changes

2025-01-08 12:50 UTC, fspreiss approved these changes

2025-01-08 13:06 UTC, yvonneanne approved these changes
LGTM

2025-01-08 15:30 UTC, berestovskyy approved these changes

2025-01-08 15:35 UTC, fxgst approved these changes

2025-01-08 15:42 UTC, merged