feat: Photo storage example
dfinity/examples pull request #355
Opened 2022-09-27 00:05 UTC by sea-snake

Example React application that shows how to upload files to an assets canister with the `@dfinity/assets` package.

Related PR https://github.com/dfinity/agent-js/pull/603

2022-09-28 11:35 UTC, sesi200 commented
Thank you very much for this PR! I'd like to get back to this once https://github.com/dfinity/agent-js/pull/603 is merged. Feel free to ping me when you think I should take another look

2022-10-07 09:42 UTC, sesi200 requested changes

2022-10-07 09:42 UTC, sesi200 commented on hosting/photo-storage/README.md
> +git can be installed from various package managers. DFX can be installed following the instructions [here](https://internetcomputer.org/docs/current/developer-docs/build/install-upgrade-remove).
```suggestion
git and npm can be installed from various package managers. DFX can be installed following the instructions [here](https://internetcomputer.org/docs/current/developer-docs/build/install-upgrade-remove).
```

2022-10-07 09:42 UTC, sesi200 commented on hosting/photo-storage/README.md
> +Before deployment on the IC, the hardcoded identity should be replaced by an authentication method e.g. Internet Identity.
```suggestion
Before deployment on the IC, the hardcoded identity (defined in `src/App.js`) should be replaced by an authentication method e.g. Internet Identity.
```

2022-10-07 09:42 UTC, sesi200 commented on hosting/photo-storage/package.json
> +    "@dfinity/identity": "^0.13.4",
```suggestion
    "@dfinity/assets": "^0.14.0",
    "@dfinity/agent": "^0.14.0",
    "@dfinity/identity": "^0.14.0",
    "@dfinity/candid": "^0.14.0",
    "@dfinity/principal": "^0.14.0",
```
I had to do this to get it to work

2022-10-07 09:42 UTC, sesi200 commented on hosting/photo-storage/README.md
> +```
If you could add some sort of feedback if this gets forgotten that would be great! Even a simple `alert("please follow instructions in ##Authorization")` (or whatever the syntax in JS is for that) would be very helpful.

2022-10-23 00:32 UTC, sea-snake commented
Updated MR with above suggestions and fixed some bugs (replaced masonry dep with a more reliable masonry dep)

2022-11-03 12:35 UTC, sesi200 commented
Also, the `rust-basic-bitcoin` failed test will be fixed in master in a few minutes

2022-12-10 23:53 UTC, sea-snake commented
> Looking nice, thanks a lot! Any chance you can also add a very basic e2e test to alert us (me) when a dfx update breaks the example? [This](https://github.com/dfinity/examples/blob/master/.github/workflows/rust-basic-bitcoin-example.yml) is a good example you could work from. It doesn't need to be anything fancy

Added a workflow that checks if the project builds and deploys successfully.

2022-12-12 10:19 UTC, sesi200 commented
With `npm i` and `npm run build` I get the following error:
```
Failed to compile.

Module not found: Error: Can't resolve 'assert' in '/Users/ssiff/Desktop/examples/hosting/photo-storage/node_modules/@dfinity/identity/lib/esm/identity'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }
```

Is this a problem introduced by myself or something wrong with the code?

2022-12-14 10:44 UTC, sea-snake commented
> With `npm i` and `npm run build` I get the following error:
> 
> ```
> Failed to compile.
> 
> Module not found: Error: Can't resolve 'assert' in '/Users/ssiff/Desktop/examples/hosting/photo-storage/node_modules/@dfinity/identity/lib/esm/identity'
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
> 	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
> 	- install 'assert'
> If you don't want to include a polyfill, you can use an empty module like this:
> 	resolve.fallback: { "assert": false }
> ```
> 
> Is this a problem introduced by myself or something wrong with the code?

Seems like a problem in `@dfinity/identity 0.14.1`, updating dependencies to `0.15.0` seems to fix it.

2022-12-15 10:32 UTC, sesi200 commented
Thank you for fixing it that quickly! Can confirm it work now. Thank you very much for contributing!

2022-12-15 10:33 UTC, merged