feat: SvelteKit template
dfinity/examples pull request #385
Opened 2022-11-11 09:45 UTC by peterpeterparker

A Hello World SvelteKit template.

TODO: move existing svelte starter kit to subfolder "svelte"

2022-11-25 10:58 UTC, sesi200 requested changes
Any chance we can add some minimal testing to demonstrate the example at least deploys? e.g. like this: https://github.com/dfinity/examples/blob/master/.github/workflows/motoko-calc-example.yaml

2022-11-25 10:58 UTC, sesi200 commented on svelte/sveltekit-starter/README.md
> +You can get $20 worth of cycles for free from the Cycles Faucet, if you have a GitHub account. To claim them, follow [this guide](https://smartcontracts.org/docs/quickstart/cycles-faucet.html).
```suggestion
You can get $20 worth of cycles for free from the [Cycles Faucet](faucet.dfinity.org).
```

2022-11-25 11:02 UTC, peterpeterparker commented on svelte/sveltekit-starter/dfx.json
> +	"dfx": "0.12.0",
>= `v0.12.0` is a must because the `npm run generate` introduced by `v0.12.0` is a breaking change

2022-11-25 11:04 UTC, peterpeterparker commented on svelte/sveltekit-starter/README.md
> +dfx deploy
As documented in the README, use `https://ryjl3-tyaaa-aaaaa-aaaba-cai.localhost:8000`

`http://127.0.0.1:8000/?canisterId=ryjl3-tyaaa-aaaaa-aaaba-cai` won't work.

2022-11-25 11:05 UTC, peterpeterparker commented
> Any chance we can add some minimal testing to demonstrate the example at least deploys? e.g. like this: https://github.com/dfinity/examples/blob/master/.github/workflows/motoko-calc-example.yaml

That would be nice, cool idea, but I personally won't provide it - no time. If you could, that would be super.

2022-12-01 20:58 UTC, peterpeterparker commented
@sesi200 what's blocking here?

2022-12-02 08:07 UTC, sesi200 approved these changes

2022-12-02 08:07 UTC, sesi200 commented
I mean we can merge it, it'll just be outdated/broken at some point, but that's the case for the other svelte example(s?) too

2022-12-02 08:07 UTC, merged

2022-12-02 08:11 UTC, peterpeterparker commented
They are 😉

cf https://forum.dfinity.org/t/error-when-deploying-svelte-examples-from-dfinity-samples-bank/16983/2?u=peterparker

Thanks for the review